# Generated by Django 6.0.3 on 2026-03-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('venue', 'Venue'), ('equipment', 'Equipment'), ('volunteer', 'Volunteer')], max_length=20),
        ),
    ]
