# Generated by Django 6.0.3 on 2026-03-29 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('venue', 'Venue & Logistics'), ('catering', 'Catering'), ('marketing', 'Marketing & Promotion'), ('equipment', 'Equipment & Tech'), ('decoration', 'Decoration'), ('speaker', 'Speaker & Honorarium'), ('transport', 'Transport'), ('misc', 'Miscellaneous')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('estimated', 'Estimated'), ('approved', 'Approved'), ('spent', 'Spent')], default='estimated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
